version: '2'
services:
  play-caller:
    image: ilyazinkovich/play-caller:1.0-SNAPSHOT
    container_name: play-caller
    ports:
      - 9000:9000
    networks:
      - esnet


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=elastic-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  es-volume:


networks:
  esnet: